fix: add cache context
thunder/entity_reference_override pull request #12
Opened 2021-07-27 15:49 UTC by chrfritsch

2021-07-27 15:49 UTC, chrfritsch commented
This fixes #11

2021-08-02 13:24 UTC, ol0lll requested changes

2021-08-02 13:24 UTC, ol0lll commented on src/Plugin/Field/FieldType/EntityReferenceOverrideItem.php
> -    if ($name == 'entity' && !empty($this->values['overwritten_property_map'])) {
entity_reference_override_property_map

2021-08-02 13:24 UTC, ol0lll commented on entity_reference_override.module
> +  if (isset($entity->overwritten_path)) {
`$entity->overwritten_path` could be `$entity->entity_reference_override`

2021-08-02 13:24 UTC, ol0lll commented on entity_reference_override.module
> +    $build['#cache']['keys'][] = 'overridden_reference_field:' . $entity->overwritten_path;
`$build['#cache']['keys'][] = 'entity_reference_override:' . $entity-> entity_reference_override;`

2021-08-02 14:06 UTC, ol0lll approved these changes
lgtm

2021-08-02 14:07 UTC, merged